CREATE TABLE ACCOUNTS (
    ACCOUNT_NUMBER SERIAL PRIMARY KEY,
    CUSTOMER_ID INT not null,
    ACCOUNT_TYPE VARCHAR(100) NOT NULL,
    BRANCH_ADDRESS VARCHAR(100) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    UPDATED_AT DATE DEFAULT NULL,
    UPDATED_BY VARCHAR(20) DEFAULT NULL
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID SERIAL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_EMAIL VARCHAR(100) NOT NULL,
    MOBILE_NUMBER VARCHAR(20) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    UPDATED_AT DATE DEFAULT NULL,
    UPDATED_BY VARCHAR(20) DEFAULT NULL
);